# Generated by Django 4.2.3 on 2023-07-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookShopApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=100)),
                ('from_surname', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('is_member', models.BooleanField(default=False)),
            ],
        ),
    ]
